#!/bin/bash

## Functions
function swap_on(){
  mount="sudo -A mount /dev/sdb1 ~/usb-drive"
  swapon="sudo swapon ~/usb-drive/swapfile1"
}

## Commands
update="sudo pacman -Syyu --noconfirm"
dependencies="sudo pacman -Syyu bash coreutils findutils realpath curl cron"
process="ps aux | grep node"
shutdown="sudo shutdown -h now"
yaourt="yaourt binfmt-support"
dotfiles="mkdir -p ~/dev; cd ~dev/; git clone git@github.com:skilbjo/dotfiles.git"
dotfiles="cd ~/dev/dotfiles; git pull"
uptime="uptime"
cron="sudo pacman -Syu cronie --noconfirm"
cron="sudo systemctl enable --now cronie.service"
postgres="sudo pacman -Syu postgresql --noconfirm"
postgres="sudo systemctl enable --now postgresql.service"

