#!/bin/bash

## Functions
function swap_on(){
  mount="sudo -A mount /dev/sdb1 ~/usb-drive"
  swapon="sudo swapon ~/usb-drive/swapfile1"
}

## Commands
update="sudo pacman -Syyu --noconfirm"
dotfiles="cd ~/dev/dotfiles; git pull"

software="sudo pacman -Su keychain --noconfirm"
install_software="sudo pacman -S PACKAGE_HERE --noconfirm"
shutdown="sudo shutdown -h now"
reboot="sudo reboot"
uptime="uptime"

